### ISSUE TITLE
Mas -> Twi : cut toots to fit in tweets, and add link to full toot

### ISSUE THREAD

**Issue by Siltaar** [halcy/MastodonToTwitter#39]
Hi,

Everything fitted in the subject. I thought my 500chars toots would appears like : 
« Begining of my interesting toot […] http://mamot.fr/link/to/toot »

When toots are too long to fit in 140 characters.

**Comment by Siltaar** [comment]
There is a splitting feature in the code, but it's not actually working as I can see.
Short URL where reported to length 24 chars during installation.

**Comment by halcy** [comment]
Hm. Do feel free to add this as a configurable feature, but plenty of people prefer the splitting approach (which SHOULD be working - how is it breaking for you?)

**Comment by Siltaar** [comment]
One success, one failure:
```
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tweeting any toots after toot 804189
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tooting any tweets after tweet 856911892979298304
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Updated expected short URL length: Is now 24
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Found new toots, processing:
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Toot bigger 140 characters, need to split...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: new part
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Encountered error after 3 retries. Not retrying.
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Finished toot processing, resting until next toots.
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Found new toots, processing:
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Toot smaller 140 chars, posting directly...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tweeting "plop"...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Finished toot processing, resting until next toots.
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Found new toots, processing:
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Toot smaller 140 chars, posting directly...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Downloading https://mamot.fr/system/media_attachments/files/000/062/791/original/9274d37d58889281.jpg?1493283046
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Uploading /tmp/tmpeitfn6go.jpeg
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Encountered error after 3 retries. Not retrying.
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Finished toot processing, resting until next toots.
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Found new toots, processing:
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Toot smaller 140 chars, posting directly...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tweeting ""...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tweeting ""...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tweeting ""...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Tweeting ""...
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Encountered error after 3 retries. Not retrying.
Apr 28 11:07:37 redwall MastodonToTwitter.sh[7863]: Finished toot processing, resting until next toots.
```

All logs appeared today, following a new failure.
```logs
Apr 28 11:07:40 redwall systemd[1]: MastodonToTwitter.service holdoff time over, scheduling restart.
Apr 28 11:07:40 redwall systemd[1]: Stopping crossposter mastodon <-> twitter...
Apr 28 11:07:40 redwall systemd[1]: Starting crossposter mastodon <-> twitter...
Apr 28 11:07:40 redwall systemd[1]: Started crossposter mastodon <-> twitter.
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: Traceback (most recent call last):
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/.virtualenvs/mas2twi/lib/python3.4/site-packages/mastodon/Mastodon.py", line 673, in __api_request
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: response = response_object.json()
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/.virtualenvs/mas2twi/lib/python3.4/site-packages/requests/models.py", line 866, in json
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: return complexjson.loads(self.text, **kwargs)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: return _default_decoder.decode(s)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: raise ValueError(errmsg("Expecting value", s, err.value)) from None
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: ValueError: Expecting value: line 1 column 1 (char 0)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: Traceback (most recent call last):
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/.virtualenvs/mas2twi/lib/python3.4/site-packages/mastodon/Mastodon.py", line 673, in __api_request
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: response = response_object.json()
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/.virtualenvs/mas2twi/lib/python3.4/site-packages/requests/models.py", line 866, in json
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: return complexjson.loads(self.text, **kwargs)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: return _default_decoder.decode(s)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: raise ValueError(errmsg("Expecting value", s, err.value)) from None
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: ValueError: Expecting value: line 1 column 1 (char 0)
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: During handling of the above exception, another exception occurred:
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: Traceback (most recent call last):
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/MastodonToTwitter/MastodonToTwitter.py", line 220, in <module>
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: ma_account_id = mastodon_api.account_verify_credentials()["id"]
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/.virtualenvs/mas2twi/lib/python3.4/site-packages/mastodon/Mastodon.py", line 289, in account_verify_credentials
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: return self.__api_request('GET', '/api/v1/accounts/verify_credentials')
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: File "/home/siltaar/.virtualenvs/mas2twi/lib/python3.4/site-packages/mastodon/Mastodon.py", line 677, in __api_request
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: raise MastodonAPIError("Could not parse response as JSON, response code was %s, bad json content was '%s'" % (response_object.status_code, response_object.content))
Apr 28 11:07:40 redwall MastodonToTwitter.sh[19143]: mastodon.Mastodon.MastodonAPIError: Could not parse response as JSON, response code was 502, bad json content was 'b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <title>We\'re sorry, but something went wrong</title>\n  <meta name="viewport" content="width=device-width,initial-scale=1">\n  <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">\n  <style>\n    body {\n      font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif;\n      background: #282c37;\n      color: #9baec8;\n      text-align: center;\n      margin: 0;\n      padding: 20px;\n    }\n\n    .dialog img {\n      display: block;\n      margin: 20px auto;\n      margin-top: 50px;\n      max-width: 600px;\n      width: 100%;\n      height: auto;\n    }\n\n    .dialog h1 {\n      font: 20px/28px -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif;\n      font-weight: 400;\n    }\n  </style>\n</head>\n\n<body>\n  <div class="dialog">\n    <img src="/oops.png" alt="Mastodon" />\n\n    <div>\n      <h1>We\'re sorry, but something went wrong.</h1>\n    </div>\n  </div>\n</body>\n</html>\n''
Apr 28 11:07:40 redwall systemd[1]: MastodonToTwitter.service: main process exited, code=exited, status=1/FAILURE
Apr 28 11:07:40 redwall systemd[1]: Unit MastodonToTwitter.service entered failed state.
Apr 28 11:07:40 redwall systemd[1]: MastodonToTwitter.service holdoff time over, scheduling restart.
Apr 28 11:07:40 redwall systemd[1]: Stopping crossposter mastodon <-> twitter...
Apr 28 11:07:40 redwall systemd[1]: Starting crossposter mastodon <-> twitter...
Apr 28 11:07:40 redwall systemd[1]: MastodonToTwitter.service start request repeated too quickly, refusing to start.
Apr 28 11:07:40 redwall systemd[1]: Failed to start crossposter mastodon <-> twitter.
Apr 28 11:07:40 redwall systemd[1]: Unit MastodonToTwitter.service entered failed state.
```

**Comment by Siltaar** [comment]
Created https://github.com/halcy/MastodonToTwitter/pull/40 regarding cut stuff.

**Comment by Siltaar** [comment]
Was a locale problem on my side.
