### ISSUE TITLE
Traceback: Key error: 'rel'

### ISSUE THREAD

**Issue by bplein** [halcy/MastodonToTwitter#50]
Launching MastodonToTwitter.py (or running it as a service), I get:

`# ./MastodonToTwitter.py 
Tweeting any toots after toot 12387
Tooting any tweets after tweet 877224399400730624
Updated expected short URL length: Is now 24
Traceback (most recent call last):
  File "./MastodonToTwitter.py", line 246, in <module>
    new_toots = mastodon_api.account_statuses(ma_account_id, since_id = since_toot_id)
  File "/home/bill/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 364, in account_statuses
    return self.__api_request('GET', '/api/v1/accounts/' + str(id) + '/statuses', params)
  File "/home/bill/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 963, in __api_request
    if url['rel'] == 'next':
KeyError: 'rel'`

**Comment by bplein** [comment]
Using Mastodon 1.4.3

**Comment by hazelybell** [comment]
Posting me too like some brain-dead AOLer

**Comment by hazelybell** [comment]
Problem is Mastodon.py 1.0.8
workaround:
`pip uninstall Mastodon.py ; pip install Mastodon.py==1.0.7 `
